"""initial migration

Revision ID: a823df47e570
Revises: 4fa061538df5
Create Date: 2025-05-16 15:57:06.860133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a823df47e570'
down_revision: Union[str, None] = '4fa061538df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'SEARCH', 'UPLOAD', 'DOWNLOAD', 'SHARE', 'COMMENT', 'RATE', 'SYSTEM', 'ERROR', name='activitytype'), nullable=False),
    sa.Column('category', sa.Enum('AUTHENTICATION', 'MEMORY', 'FILE', 'USER', 'SYSTEM', 'AUDIT', name='activitycategory'), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activities_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ticket_responses')
    op.alter_column('ticket_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('ticket_comments_ticket_id_fkey', 'ticket_comments', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ticket_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('ticket_history_ticket_id_fkey', 'ticket_history', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_history', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_constraint(None, 'ticket_history', type_='foreignkey')
    op.create_foreign_key('ticket_history_ticket_id_fkey', 'ticket_history', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('ticket_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_constraint(None, 'ticket_comments', type_='foreignkey')
    op.create_foreign_key('ticket_comments_ticket_id_fkey', 'ticket_comments', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('ticket_comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_table('ticket_responses',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='ticket_responses_ticket_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ticket_responses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ticket_responses_pkey')
    )
    op.drop_table('activities')
    # ### end Alembic commands ###
