"""add user_role

Revision ID: ee69b66c05ab
Revises: 05eae4dc8523
Create Date: 2025-05-13 16:08:28.581445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee69b66c05ab'
down_revision: Union[str, None] = '05eae4dc8523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing foreign key constraints
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 
                FROM information_schema.table_constraints 
                WHERE constraint_name = 'role_permissions_permission_id_fkey' 
                AND table_name = 'role_permissions'
            ) THEN
                ALTER TABLE role_permissions DROP CONSTRAINT role_permissions_permission_id_fkey;
            END IF;
            
            IF EXISTS (
                SELECT 1 
                FROM information_schema.table_constraints 
                WHERE constraint_name = 'role_permissions_role_id_fkey' 
                AND table_name = 'role_permissions'
            ) THEN
                ALTER TABLE role_permissions DROP CONSTRAINT role_permissions_role_id_fkey;
            END IF;
        END $$;
    """)
    
    # Keep VARCHAR(36) type for permissions table
    op.execute('ALTER TABLE permissions ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR(36)')
    
    # Recreate foreign key constraints with CASCADE
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###
